### ISSUE TITLE
Advancedenchant on armor sets

### ISSUE THREAD

**Issue by kahlilnc** [N3kas/AdvancedSets#13]
The enchantment: https://hastebin.com/yiluwoviku.xml
Armor set: https://hastebin.com/ruwiwopiso.sql
Error: https://hastebin.com/juroqorafo.md
Can't get any custom enchantment to work on armor sets 😭 
Using ver 1.1.8

**Comment by GC-spigot** [comment]
Don't use hastebin, they delete pastes 24 hours after last click.
