### ISSUE TITLE
New Event

### ISSUE THREAD

**Issue by Courkie** [N3kas/AdvancedSets#14]
I noticed there are events such as

Defense:

Attack:

Shift:

Mob Kill:

There should be an event called

Walking:

This will activate when walking and will activate whatever you choose to put under there and work like any other events.

This is useful for the repair armor thing and the heal player thing.

**Comment by GC-spigot** [comment]
That is very inefficient and will not be added (unless you want your server to lag with more than 50 players online). Use Passive event and timers (explained in the same file) to achieve this.
