### ISSUE TITLE
Feature Issues

### ISSUE THREAD

**Issue by Courkie** [N3kas/AdvancedSets#16]
Timer doesn't work as well as the Dodge ability.
The timer was tested awhile back and you assisted me in the discord and told me you'll check it out later.
Please fix this soon ^

The dodge ability was recently tested, I had a friend come with KA and constantly attack me. the chances were originally at 25%.
I eventually raised it to 90%.
I tried restarting the server after editing the config and getting a brand new set but it wasn't helping.

https://hastebin.com/imisewatem.sql

^ My set config

**Comment by GC-spigot** [comment]
Works for me. If you still have this issue after the update feel free to open another ticket.
