### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Courkie** [N3kas/AdvancedSets#4]
Chance to be healed to full health when being attacked
+
Similar to the last request, add %attacker/wearer% 
so specific items do more damage if the player is wearing or holding a certain item
For example:

Swords do 25% more damage to bow users.

Or

Bows do 75% more damage to axe users

Or

Weapons do 50% less damage but bows do 150% more damage

^^
Find a way to implement systems like these.

**Comment by GC-spigot** [comment]
First suggestion added, others will be added later on.
